---

- name: Maintain Linux installation
  hosts: all
  gather_facts: true

  vars_files:
    - "vars/{{ ansible_facts['distribution'] }}.yaml"
    - vars/common.yaml
    - vars/git.yaml

  tasks:
    - name: Include dnf role
      when: ansible_facts['distribution'] == "Fedora"
      include_role:
        name: dnf

    - name: Include repositories role
      when: (ansible_facts['distribution'] == "Fedora") or (ansible_facts['distribution'] == "OpenSuse")
      include_role:
        name: repositories

    - name: Include pacman role
      when: ansible_facts['distribution'] == "ArchLinux"
      include_role:
        name: pacman

    - name: Include packages role
      include_role:
        name: packages

    - name: Include pip role
      include_role:
        name: pip

    - name: Include flatpak role
      include_role:
        name: flatpak

    - name: Include common configuration roles
      include_role:
        name: "{{ current_role.name }}"
      loop:
        - name: git
        - name: emacs
        - name: nvim
        - name: tmux
        - name: gnome
        - name: shell
      loop_control:
        loop_var: current_role

# vim: ft=yaml.ansible
