---

- name: Set up Linux post-install
  hosts: all
  gather_facts: true

  vars_files:
    - "vars/{{ ansible_distribution }}.yaml"

  vars_prompt:
    - name: hostname
      private: false

  roles:
    - role: system
    - role: repositories
    - role: packages
    - role: flatpak
    - role: dnf
    - role: git
    - role: emacs
    - role: nvim
    - role: tmux
    - role: gnome
    - role: ssh
    - role: shell

# vim: ft=yaml.ansible
