#!/usr/bin/env zsh
# File: .zshrc

# Lines configured by zsh-newuser-install
HISTFILE=~/.zsh_history
HISTSIZE=10000
SAVEHIST=10000
setopt autocd beep nomatch
unsetopt extendedglob notify
bindkey -v
# End of lines configured by zsh-newuser-install
# The following lines were added by compinstall
zstyle :compinstall filename '/home/pavalos/.zshrc'

autoload -Uz compinit
compinit
# End of lines added by compinstall

# vim: ft=zsh
