# File: .bashrc

# Source global definitions
if [[ -f /etc/bashrc ]] ; then
  source /etc/bashrc
fi

# {{{ Bash settings
export HISTSIZE=10000
export HISTFILESIZE=${HISTSIZE}
export HISTCONTROL=ignoreboth
# }}}

export SUDO_EDITOR=nvim
export VISUAL=nvim
export EDITOR=nvim

export PAGER="most"
export MANROFFOPT="-c"
export MANPAGER="sh -c 'col -bx | bat -l man -p'"

if [[ $- != *i* ]] ; then
  return # Non-interactive shell
fi

source ~/.bash-prompt.sh
source ~/.bash_aliases

# vim: fdm=marker
